# Generated by Django 2.1.3 on 2018-11-27 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddBattery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bat_name', models.CharField(max_length=10)),
                ('zone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AddComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=10)),
                ('zone', models.IntegerField()),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='CreateBattery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_capacity', models.IntegerField()),
                ('soc_min', models.IntegerField()),
                ('soc_max', models.IntegerField()),
                ('base_cost', models.FloatField()),
                ('energy_cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CreateSolar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_capacity', models.IntegerField()),
                ('base_cost', models.FloatField()),
                ('perw_cost', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='addbattery',
            name='createbattery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimizer.CreateBattery'),
        ),
    ]
