# Generated by Django 2.1.3 on 2018-11-28 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddBattery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bat_name', models.CharField(max_length=10)),
                ('zone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AddComponent',
            fields=[
                ('comp_name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('comp_type', models.CharField(max_length=10)),
                ('zone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CreateDemand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CreateBattery',
            fields=[
                ('energy_capacity', models.IntegerField()),
                ('soc_min', models.IntegerField()),
                ('soc_max', models.IntegerField()),
                ('base_cost', models.FloatField()),
                ('energy_cost', models.FloatField()),
                ('component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='optimizer.AddComponent')),
            ],
        ),
        migrations.CreateModel(
            name='CreateController',
            fields=[
                ('component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='optimizer.AddComponent')),
            ],
        ),
        migrations.CreateModel(
            name='CreateConverter',
            fields=[
                ('power', models.IntegerField()),
                ('base_cost', models.FloatField()),
                ('power_cost', models.FloatField()),
                ('component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='optimizer.AddComponent')),
            ],
        ),
        migrations.CreateModel(
            name='CreateGenerator',
            fields=[
                ('power', models.IntegerField()),
                ('base_cost', models.FloatField()),
                ('fuel_cost', models.FloatField()),
                ('component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='optimizer.AddComponent')),
            ],
        ),
        migrations.CreateModel(
            name='CreateGrid',
            fields=[
                ('energy_cost', models.FloatField()),
                ('nm_allowed', models.BooleanField(default=False)),
                ('component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='optimizer.AddComponent')),
            ],
        ),
        migrations.CreateModel(
            name='CreateSolar',
            fields=[
                ('system_capacity', models.IntegerField()),
                ('base_cost', models.FloatField()),
                ('perw_cost', models.FloatField()),
                ('component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='optimizer.AddComponent')),
            ],
        ),
        migrations.AddField(
            model_name='addbattery',
            name='createbattery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimizer.CreateBattery'),
        ),
    ]
