# Generated by Django 2.1.3 on 2018-11-26 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateBattery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bat_name', models.CharField(max_length=10)),
                ('energy_capacity', models.IntegerField()),
                ('soc_min', models.IntegerField()),
                ('soc_max', models.IntegerField()),
                ('base_cost', models.FloatField()),
                ('energy_cost', models.FloatField()),
            ],
            options={
                'managed': True,
            },
        ),
    ]
