# Generated by Django 2.0.9 on 2018-12-17 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createbattery',
            name='id',
        ),
        migrations.AlterField(
            model_name='createbattery',
            name='component',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='optimizer.AddComponent'),
        ),
    ]
